# Conda environment for Malaria Transmission Model
# Create with: conda env create -f environment.yml
# Activate with: conda activate malaria-model

name: malaria-model
channels:
  - conda-forge
  - defaults

dependencies:
  # Python
  - python>=3.8
  
  # Core scientific computing
  - numpy>=1.21.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  
  # Visualization
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  
  # Jupyter notebook
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - ipywidgets>=7.6.0
  - notebook>=6.4.0
  
  # Development tools
  - pytest>=6.2.0
  - black>=21.0
  - flake8>=3.9.0
  
  # Data handling
  - openpyxl>=3.0.0
  
  # R integration (optional)
  - r-base>=4.0
  - r-tidyverse
  - r-deSolve
  - r-ggplot2
  - r-knitr
  
  # Additional utilities
  - pip
  
  # Install additional packages via pip
  - pip:
    - pytest-cov>=2.12.0

